[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Cache de dependencias para acelerar builds
[[plugins]]
  package = "@netlify/plugin-cache"
