[functions]
directory = "netlify/functions"

[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
